---
- name: Setup Apache on webservgrp
  hosts: websrvgrp
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
    

    - name: Start & Enable apache2
      service:
        name: apache2
        state: started
        enabled: yes

- name: Stetup Mysql serviece
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: Install mysql-server
      yum:
        name: mariadb-server
        state: present

    - service:
        name: mariadb
        state: started
        enabled: yes



   
