---
- name: Setup Apache on webservgrp
  hosts: websrvgrp
  become: yes
  vars:
    webfile: files/index.html
    webdestdir: /var/www/html/
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
    

    - service:
        name: apache2
        state: started
        enabled: yes


    - name: Deploy index.html file
      copy:
        src: "{{webfile}}"
        dest: "{{webdestdir}}"
        backup: yes
      notify:
        - Restart apache2

   
  handlers:
    - name: Restart apache2
      service:
        name: apache2
        state: restarted   
