---
- name: Setup Apache on webservgrp
  hosts: websrvgrp
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
    

    - service:
        name: apache2
        state: started
        enabled: yes


    - name: Deploy index.html file
      copy:
        src: file/index.html
        dest: /var/www/html
        backup: yes
   
    - name: Restart apache2
      service:
         name: apache2
         state: restarted
